### ISSUE TITLE
Seeking (horizontal swipe) not working

### ISSUE THREAD

**Issue by BibleBeliever** [blueberry6401/xposed_youtube-swipe-to-seek#15]
Hi,

Thanks for your great module, but unfortunately the latest version of YouTube isn't working properly with this mod. Horizontal sweeping isn't working. I'm on MM. 

Thanks

**Comment by tamjidhasan73** [comment]
I have the same problem, horizontal swipe is not working, vertical swipe (sound) is working though, im on oxygen os 2.2.1 (android 5.1)

**Comment by Raijin56** [comment]
The same here. The volume is working but the seek not. Sometimes it responds, and moves back or forward 2 secs.

I'm using a Samsung Galaxy S7 Edge with Android 6.0.1.

**Comment by abhi08638** [comment]
Same issue but for now you can still seem by swiping in a diagonal. Bottom left to top right is forward and bottom right to top left is backward

**Comment by brbsix** [comment]
@abhi08638 Weird. I almost didn't believe you until I checked. Can confirm seeking works as you described on the latest YouTube release v11.35.60. I was worried YouTube had changed the VR button hook method used by this app but apparently not... This is promising!

**Comment by abhi08638** [comment]
Yeah I was wiping a smudge on my screen and got lucky with this discovery. It's kind of awkward because it sometimes triggers the volume but it's better than nothing

**Comment by brbsix** [comment]
So I created a debug build of the APK to try to see what's going on... Here's what it looks like with working swipe-to-seek:

```
                 Xposed  I  YoutubeHooker: viewMode field data: WATCH_WHILE_FULLSCREEN
                         I  YoutubeHooker: touched down, x=817, y=798
          SwipeDetector  D  orix 817 oriy 798; x 830 y 790; xmil 0 ymil 0
                         D  orix 817 oriy 798; x 847 y 781; xmil 1 ymil -1
                         D  orix 817 oriy 798; x 855 y 777; xmil 2 ymil -1
                         D  orix 817 oriy 798; x 863 y 773; xmil 2 ymil -1
                         D  orix 817 oriy 798; x 868 y 770; xmil 3 ymil -1
                 Xposed  I  YoutubeHooker: swipe started
                         I  YoutubeHooker: current pos=29950, video duration=391000
                         I  YoutubeHooker: fullScr=true, maxMusicVol=15, currentMusicVol=12
          SwipeDetector  D  orix 817 oriy 798; x 878 y 767; xmil 3 ymil -1
                 Xposed  I  YoutubeHooker: swipe 3, seek 2
          SwipeDetector  D  orix 817 oriy 798; x 882 y 765; xmil 4 ymil -2
                 Xposed  I  YoutubeHooker: swipe 4, seek 2
          SwipeDetector  D  orix 817 oriy 798; x 888 y 761; xmil 4 ymil -2
                         D  orix 817 oriy 798; x 892 y 758; xmil 4 ymil -2
          SwipeDetector  D  orix 817 oriy 798; x 895 y 756; xmil 4 ymil -2
                         D  orix 817 oriy 798; x 899 y 754; xmil 5 ymil -2
                 Xposed  I  YoutubeHooker: swipe 5, seek 3
          SwipeDetector  D  orix 817 oriy 798; x 903 y 752; xmil 5 ymil -2
                         D  orix 817 oriy 798; x 908 y 750; xmil 5 ymil -3
                 Xposed  I  YoutubeHooker: swipe 5, seek 3
          SwipeDetector  D  orix 817 oriy 798; x 913 y 747; xmil 6 ymil -3
                 Xposed  I  YoutubeHooker: swipe 6, seek 4
          SwipeDetector  D  orix 817 oriy 798; x 919 y 744; xmil 6 ymil -3
                         D  orix 817 oriy 798; x 925 y 741; xmil 6 ymil -3
                         D  orix 817 oriy 798; x 929 y 739; xmil 7 ymil -3
                 Xposed  I  YoutubeHooker: swipe 7, seek 4
          SwipeDetector  D  orix 817 oriy 798; x 934 y 737; xmil 7 ymil -3
                         D  orix 817 oriy 798; x 937 y 736; xmil 7 ymil -3
                         D  orix 817 oriy 798; x 940 y 734; xmil 7 ymil -4
                 Xposed  I  YoutubeHooker: swipe 7, seek 4
          SwipeDetector  D  orix 817 oriy 798; x 944 y 732; xmil 7 ymil -4
                         D  orix 817 oriy 798; x 945 y 731; xmil 8 ymil -4
                 Xposed  I  YoutubeHooker: swipe 8, seek 5
          SwipeDetector  D  orix 817 oriy 798; x 947 y 729; xmil 8 ymil -4
                         D  orix 817 oriy 798; x 949 y 729; xmil 8 ymil -4
                         D  orix 817 oriy 798; x 951 y 729; xmil 8 ymil -4
                         D  orix 817 oriy 798; x 952 y 729; xmil 8 ymil -4
                 Xposed  I  YoutubeHookerswipe stopped
    TransportController  D  seekTo in TransportControls
```

And then here's what happens when it doesn't work:

```
                 Xposed  I  YoutubeHooker: viewMode field data: WATCH_WHILE_FULLSCREEN
                         I  YoutubeHooker: touched down, x=685, y=775
          SwipeDetector  D  orix 685 oriy 775; x 685 y 775; xmil 0 ymil 0
                         D  orix 685 oriy 775; x 706 y 770; xmil 1 ymil 0
                         D  orix 685 oriy 775; x 732 y 767; xmil 2 ymil 0
```

So YoutubeHooker hooks into the YouTube application with SwipeDetector. It's listening for any touch event. It gets an onTouchedDown. SwipeDetector recognizes 3 motion events with a total of 2 mils horizontal movement. The swipe threshold is 2 mils (so it won't count as a swipe event until it's at 3 mils). So the 'swipe started' isn't reached and nothing happens. Something appears to be cancelling the swipe immediately before the threshold is reached. But for some reason, it doesn't get cancelled if there is vertical movement.

Maybe a Java developer has a better idea of what's going on here. Why would the swipe detection differ between different versions of YouTube?

**Comment by gentri86** [comment]
I am not familiar with the English language.
If the swipe 40deg angle to work.

**Comment by blueberry6401** [comment]
Finally I got times to fix this, I'm so sorry for taking it too long.
I'll do test for a day, if there is no other issues I'll post it to xposed repo.

**Comment by ghhp** [comment]
Thx so much for the great update.
