### ISSUE TITLE
Youtube 11.35.60 Update Please 

### ISSUE THREAD

**Issue by faizoo** [blueberry6401/xposed_youtube-swipe-to-seek#16]
Not working Swipe to seek on Youtube 12.35.60

**Comment by brbsix** [comment]
FYI the latest update is YouTube v11.35.60. Also there are already 2 open issues on this same issue.

See #13 #15

**Comment by blueberry6401** [comment]
Finally I got times to fix this, I'm so sorry for taking it too long.
I'll do test for a day, if there is no other issues I'll post it to xposed repo.

**Comment by brbsix** [comment]
@blueberry6401 I've been testing out the fix with v11.35.60 and v11.38.54. It works great, thank you so much!
