### ISSUE TITLE
Bug with comments section after using seek/rewind

### ISSUE THREAD

**Issue by brusyev** [blueberry6401/xposed_youtube-swipe-to-seek#18]
If I play a video while in vertical mode and try to use seek/rewind then try to scroll down in the comments section right after that, instead of scrolling down comments youtube would still do seek/rewind.

**Comment by CodiceMortem** [comment]
Same issue here, but it seems to be temporary fixed by sliding down the video to get the floating player then sliding up to get the normal player, at this point you can scroll comments again without troubles, if you use the seek/rewind function the bug will be back.
