### ISSUE TITLE
What is the oldest youtube version this module support?

### ISSUE THREAD

**Issue by charanzable** [blueberry6401/xposed_youtube-swipe-to-seek#2]
As the limitation of my phone, it cannot use the latest youtube version otherwise cannot play in HD. Just wanna to know the oldest version this module support to see if my phone can use this version to play HD videos. Thanks

**Comment by blueberry6401** [comment]
I just write this module about several days ago, so I can't tell you that. You can try it yourself, if unfortunately it doesn't work, just disable it in Xposed Installer, your system will not be affected at all.
