### ISSUE TITLE
YouTube 11.47.55 Update 

### ISSUE THREAD

**Issue by baiwei-lim** [blueberry6401/xposed_youtube-swipe-to-seek#22]
Latest YouTube update breaks YouTube swipe to seek again :(

**Comment by Nallaballivenkatasaikrishna** [comment]
Yes from 11.47.55 above updates swipe to seek not working

**Comment by blueberry6401** [comment]
Thanks for reporting, I've fixed it in 08530f2b5b04b01ef7fdee912aa19226bbf0f09d
You can now update module from xposed repository.
