### ISSUE TITLE
Not working 

### ISSUE THREAD

**Issue by Atharkhan101** [blueberry6401/xposed_youtube-swipe-to-seek#26]
Not working on micromax canvas nitro 4G E455 lollipop on latest YouTube version.

**Comment by blueberry6401** [comment]
Which YouTube version are you using?

**Comment by Atharkhan101** [comment]
The latest one. Already told you. ⁣

**Comment by blueberry6401** [comment]
I mean what exacly it is? Maybe Youtube have latest version different from
regions, languages,...
I'm on v11.47.57 (latest) and have no problem at all.
