### ISSUE TITLE
Stopped working

### ISSUE THREAD

**Issue by CommanderPirx** [blueberry6401/xposed_youtube-swipe-to-seek#40]
Just randomly stopped working altogether. Both swipe to seek and volume control.

**Comment by Poooootato69** [comment]
Same here, it no longer works for me as of today 3/20/18

**Comment by hanswurst31** [comment]
https://www.apkmirror.com/apk/google-inc/youtube/youtube-13-09-56-release/

This is the last working version.

**Comment by timea-techgirl** [comment]
Force stop and clear data of YouTube app. Works fine on the latest 13.10.59 version.

Close the issue when it works.

**Comment by CommanderPirx** [comment]
Well I'll be damned, it sure does work indeed. Thank you very much mister @malitech !
