### ISSUE TITLE
UPDATE NEEDED

### ISSUE THREAD

**Issue by newkeyword** [blueberry6401/xposed_youtube-swipe-to-seek#41]
Current version is no more compatible with the newest YT

**Comment by ChaliceChore** [comment]
for me too. doesn't work with YT 13 app.

**Comment by hanswurst31** [comment]
https://www.apkmirror.com/apk/google-inc/youtube/youtube-13-09-56-release/

stick with this.

**Comment by timea-techgirl** [comment]
Force stop and clear data of YouTube app. Works fine on the latest 13.10.59 version.

Close the issue when it works.

**Comment by k-o-t-s** [comment]
Force stopping and clearing data works indeed on 13.10.59 but only temporarily. If you reboot the device or quit YT app, then swipe gestures will not work next time

**Comment by newkeyword** [comment]
Downgrading app or some other methods may work but i think Xposed module update is a MUST

**Comment by wolcano** [comment]
I am experiencing crashes as well (clearing Youtube app cache helps for first run), but it seems there is some collision when I use these 3 xposed modules at the same time:
- youtube swipe to seek
- youtube adaway
- youtube background playback

when I disable one of them, no crashes occur

**Comment by k-o-t-s** [comment]
I don't have YT background playback installed but I do have YT adaway and even if I disable it, YT swipe to seek still has the same issue. Nice find though, wolcano! It may help the developer fix this module.

**Comment by blueberry6401** [comment]
Sorry everyone, I'm using Android anymore so I can't keep developing this.
This repo will be archived.
