### ISSUE TITLE
No seeking in non-fullscreen possible 

### ISSUE THREAD

**Issue by Vankog** [blueberry6401/xposed_youtube-swipe-to-seek#7]
YT v. 11.19.56 nodpi
Module v. 1.1
Device: Tablet (NVidia Shield) 

In non-fullscreen, seeking via swipe does not work. In full screen both functions are working. 
According to your description, seeking should still work in contrast to volume control due to obvious reasons.

**Comment by Vankog** [comment]
Just realized that it is only the case for landscape, possibly because right swipe does also belittle the video in this format. In portrait it's working.

**Comment by blueberry6401** [comment]
That's right. In landscape mode the gestures is for expanding or dismissing the player, so the module will not work here. Also in portrait up-down gesture doesn't work because it's for expanding or minimizing player.
