### ISSUE TITLE
Volume change in landscape non-fullscreen player 

### ISSUE THREAD

**Issue by Vankog** [blueberry6401/xposed_youtube-swipe-to-seek#8]
YT v. 11.19.56 nodpi 
Module v. 1.1 
Device: Tablet (NVidia Shield) 

Swiping up and down on the landscape non-fullscreen player randomly leads to volume changes. Often this happens on bigger swipes if you repeat it several times.

**Comment by blueberry6401** [comment]
This is mentioned in this issue #3 
Actually I fixed it already but didn't release the apk yet. I'll push it to xposed repo after done some other works.
